### ISSUE TITLE
Container Just Crashes

### ISSUE THREAD

**Issue by royaltongue** [volotat/Anagnorisis#8]
Using this `docker-compose.yml`:
```
services:
  anagnorisis:
    container_name: anagnorisis
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      RUNNING_IN_DOCKER: true
    volumes:
      - ${dcs}/anagnorisis/app:/app
      - ${dcs}/anagnorisis/app/project_data:/app/project_data
    ports:
      - "127.0.0.1:${EXTERNAL_PORT:-5001}:5001" # Map the external port to the internal port
    restart: no
```

The container will start, display this in the logs:
```
==========
== CUDA ==
==========

CUDA Version 12.4.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.
```

And then crash
